### ISSUE TITLE
LICENCE?

### ISSUE THREAD

**Issue by iago-suarez** [KU-CVLAB/CATs-PlusPlus#3]
Thanks for your great paper. Since this work is an extension of https://github.com/SunghwanHong/Cost-Aggregation-transformers, I guess the license of the code is still [GPL-3.0 license](https://github.com/SunghwanHong/Cost-Aggregation-transformers/blob/main/LICENSE).

Could you please confirm this? And maybe add the LICENCE file to the repository :)

Thank you in advance!

**Comment by SunghwanHong** [comment]
Sorry for the late reply.

Hi, Yes, you can assume that the license is the same. 
We will add it in this repo very soon (after CVPR submission).
